image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/sethwebster/airport_lookup_api:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  script:
    - echo "PASS $DOCKER_PASSWORD"
    - docker login registry.gitlab.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE}
    - docker tag ${CONTAINER_IMAGE} registry.gitlab.com/sethwebster/airport_lookup_api:latest
    - docker push ${CONTAINER_IMAGE}
    - docker push registry.gitlab.com/sethwebster/airport_lookup_api:latest

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - echo "The tokens  $USER_TOKEN  ${CERTIFICATE_AUTHORITY_DATA}"
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" ./kubernetes/deployment.yaml
    - kubectl apply -f ./kubernetes/deployment.yaml
