apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airport-icao-lookup
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: airport-icao-lookup
    spec:
      containers:
        - name: airport-icao-lookup
          image: registry.gitlab.com/sethwebster/airport_lookup_api:33
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: aiport-lookup-config
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1025Mi"
          #     cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 5

      imagePullSecrets:
        - name: regcred
