apiVersion: v1
kind: Service
metadata:
  name: airport-icao-lookup-service
  namespace: default
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: airport-icao-lookup
  sessionAffinity: None
  type: NodePort
